USE `dbsimi`;
DROP procedure IF EXISTS `SP_VOUCHER_LIST`;

DELIMITER $$
CREATE PROCEDURE `SP_VOUCHER_LIST`()
BEGIN
	SELECT 
    COD AS CODIGO,
    SEC AS SECUENCIA,
    DESCRIPCION,
    NRODOCUMENTO,
    IMPORTE,
    FECHA,
    HORA,
    COMILLA AS ESTADO
    FROM TMVOUCHER;
END$$

DELIMITER ;

